plugins {
    id 'application'
    id 'io.qameta.allure' version '2.11.1'
}

allure {
    adapter.autoconfigure = true
    version = '2.20.1'
}

repositories {
    mavenCentral()
}

dependencies {
    // TestNG
    testImplementation 'org.testng:testng:7.9.0'
    // Selenium Java
    implementation 'org.seleniumhq.selenium:selenium-java:4.18.1'
    // WebDriverManager
    implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'
    // https://mvnrepository.com/artifact/io.cucumber/cucumber-java
    implementation("io.cucumber:cucumber-java:7.23.0")
    // https://mvnrepository.com/artifact/io.cucumber/cucumber-junit
    testImplementation("io.cucumber:cucumber-junit:7.23.0")
}

tasks.register('cucumberTest', Test) {


    // Configura que corra sólo la clase runner que tiene el @RunWith(Cucumber.class)
    include '**/runner/TestRunner.class'

    // Pasa todas las propiedades del sistema para poder usar -Dcucumber.filter.tags etc.
    systemProperties System.getProperties()

    testLogging {
        events "passed", "failed", "skipped"
    }
}



